[project]
name = "pascals-academy-summarizer"
version = "0.1.0"
description = "PDF summarization pipeline for a Blinkist-like app"
requires-python = ">=3.9"

[tool.pytest.ini_options]
pythonpath = ["src"]
